vse: &vse
  docker:
    - image: romanzdk/new-eshop:latest

version: 2.1
jobs:
  build:
    <<: *vse
    steps:
      - checkout
      - run: npm install
      - run: npm run test
      - run: npm run build
      - persist_to_workspace:
         root: .
         paths:
            - .
  deploy:
     <<: *vse
     steps:
        - add_ssh_keys:
            fingerprints:
              - "91:e0:ff:66:5e:33:1c:08:f9:17:9e:ab:6a:04:3e:49"
        - attach_workspace:
           at: .
        - run:
           command: ansible-playbook ansible/ec2_deploy.yml --vault-password-file get_vault_pass.sh --key-file eshop-key-pair.pem

workflows:
  version: 2.1
  build:
    jobs:
      - build
      - deploy:
         requires:
            - build
         filters:
            branches:
               only: main
